run_tag: convnext_tiny_224
model_name: convnext_tiny
img_size: 224
batch_size: 32
epochs: 20
lr: 0.0003
weight_decay: 0.0001
warmup_epochs: 1
patience: 6
seed: 42
aug_mode: medium
allow_horizontal_flip: false
label_smoothing: 0.1
use_class_weights: true
loss_type: ce
mixed_precision: true
use_ema: true
ema_decay: 0.999
num_workers: 4
