run_tag: convnext_tiny_224
model_name: convnext_tiny
img_size: 224
batch_size: 32
epochs: 25
lr: 0.0001
weight_decay: 0.0001
warmup_epochs: 1
patience: 10
seed: 42
aug_mode: medium
allow_horizontal_flip: false
loss_name: ce
label_smoothing: 0.1
use_class_weights: true
loss_type: ce
mixed_precision: true
use_ema: false
ema_decay: 0.999
num_workers: 4
val_tta_crops: 1
