run_tag: debug_fast
model_name: convnext_tiny
img_size: 224
batch_size: 8
epochs: 2
lr: 0.0003
weight_decay: 0.0001
warmup_epochs: 0
patience: 2
seed: 42
aug_mode: light
allow_horizontal_flip: false
label_smoothing: 0.05
use_class_weights: false
loss_type: ce
mixed_precision: true
use_ema: false
num_workers: 2
