run_tag: dinov2_vits14_linear
model_name: dinov2_vits14
freeze_backbone: true
head_dropout: 0.2
img_size: 224
batch_size: 32
epochs: 16
lr: 0.0005
weight_decay: 0.00005
warmup_epochs: 1
patience: 5
seed: 42
aug_mode: light
allow_horizontal_flip: false
label_smoothing: 0.05
use_class_weights: true
loss_type: ce
mixed_precision: true
use_ema: false
num_workers: 4
optional_finetune: true
finetune_min_vram_gb: 14
finetune_epochs: 8
