run_tag: effnetv2_b3_320
model_name: tf_efficientnetv2_b3
img_size: 320
batch_size: 16
epochs: 24
lr: 0.00025
weight_decay: 0.0001
warmup_epochs: 2
patience: 7
seed: 42
aug_mode: medium
allow_horizontal_flip: false
label_smoothing: 0.1
use_class_weights: true
loss_type: ce
mixed_precision: true
use_ema: true
ema_decay: 0.999
num_workers: 4
