run_tag: swin_base_224
model_name: swin_base
img_size: 224
batch_size: 16
epochs: 50
lr: 0.0002
weight_decay: 0.05
warmup_epochs: 2
patience: 10
seed: 42

aug_mode: medium
allow_horizontal_flip: false

loss_name: focal
focal_gamma: 2.0
label_smoothing: 0.05
use_class_weights: true

mixed_precision: true
use_ema: true
ema_decay: 0.999
num_workers: 4
val_tta_crops: 5
